In [1]:
import sys
sys.path.insert(0, '..')

import pandas as pd
from utils import classify_sentiment, balance_by_min_class

df = pd.read_csv('../data/ai_apps_reviews_100000.csv')

display(df.head())
display(df.tail())

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion,appName
0,2f2a48ea-b0aa-4438-9bb4-c4438c5d6379,Yuvaraj Gooty,https://play-lh.googleusercontent.com/a/ACg8oc...,nice,5,0,1.2026.097,2026-04-17 14:18:28,NaN,NaN,1.2026.097,ChatGPT
1,3772fdf1-9154-468d-9e61-4fcb2f075342,Pradeep Minz,https://play-lh.googleusercontent.com/a-/ALV-U...,very good and helpfull,5,0,1.2026.097,2026-04-17 14:18:21,NaN,NaN,1.2026.097,ChatGPT
2,c7712e3f-7613-48ce-bd50-0524fd92ff9e,George Macharia,https://play-lh.googleusercontent.com/a-/ALV-U...,gives knowledge and critical thinking,5,0,1.2026.097,2026-04-17 14:18:12,NaN,NaN,1.2026.097,ChatGPT
3,3c0b7960-895b-429a-a7fe-9164a20912a2,Physiotherapy clinic Home services Physiotherapy,https://play-lh.googleusercontent.com/a-/ALV-U...,super nice 👍,5,0,1.2026.097,2026-04-17 14:18:04,NaN,NaN,1.2026.097,ChatGPT
4,8d2a5e7c-a6c2-435e-985d-f3a3fabba97c,ss ajaira hack,https://play-lh.googleusercontent.com/a-/ALV-U...,nice help full app,4,0,1.2026.097,2026-04-17 14:17:51,NaN,NaN,1.2026.097,ChatGPT

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion,appName
233508,9ef88bc6-f29c-4aac-9717-5e0dbbd5f92e,Mayank Mishra,https://play-lh.googleusercontent.com/a-/ALV-U...,First to review.,5,0,1.240722.0,2024-07-16 18:16:53,NaN,NaN,1.240722.0,Claude
233509,e712ab42-9dbf-4dce-878f-21c2404c497c,Adarsh AS,https://play-lh.googleusercontent.com/a-/ALV-U...,The best llm ever. I love you anthropic😘,5,0,1.240722.0,2024-07-16 17:50:45,NaN,NaN,1.240722.0,Claude
233510,6c7a0e65-1173-4119-9e62-ecb09657be5c,Aksel Selyan,https://play-lh.googleusercontent.com/a-/ALV-U...,"Great job, thank your for making Claude unders...",4,1,1.240722.0,2024-07-16 17:50:35,NaN,NaN,1.240722.0,Claude
233511,04ab8d9a-8022-400a-8aa4-79de2cf80b45,kitoff sinag,https://play-lh.googleusercontent.com/a/ACg8oc...,"Phenomenal AI. Great ui, very nice of claude h...",5,3,NaN,2024-07-16 13:10:31,NaN,NaN,NaN,Claude
233512,4eb1294e-6dfa-47f9-a4fb-c0289259c1a9,Parviz Rzayev,https://play-lh.googleusercontent.com/a-/ALV-U...,"I like this app, it makes my life a little eas...",5,3,1.240722.0,2024-07-16 09:33:04,NaN,NaN,1.240722.0,Claude

In [2]:
print(df['appName'].nunique())
print(df['appName'].value_counts())

3
appName
ChatGPT    100000
Gemini     100000
Claude      33513
Name: count, dtype: int64

In [3]:
print(df['score'].value_counts())

score
5    171749
1     23230
4     22893
3     10306
2      5335
Name: count, dtype: int64

In [4]:
df['Sentiment'] = df['score'].apply(classify_sentiment)

sentiment_counts = df['Sentiment'].value_counts()
print(sentiment_counts)

Sentiment
Positive    194642
Negative     28565
Neutral      10306
Name: count, dtype: int64

In [5]:
df_balanced = balance_by_min_class(df, label_col='Sentiment', random_state=42)

print(f"Total rows: {len(df_balanced)}")
print(df_balanced['Sentiment'].value_counts())

df_balanced.to_csv('../data/ai_apps_reviews_BALANCED.csv', index=False)

Total rows: 30918
Sentiment
Negative    10306
Positive    10306
Neutral     10306
Name: count, dtype: int64